[workers]
worker ansible_host=192.168.122.185

[db]
database ansible_host=192.168.122.157

[all:vars]
ansible_user=ansible
# Используем абсолютный путь или полагаемся на дефолт. Убрал строку с ~, так как это дефолтный ключ.
student_variant=9
webapp_port=8009
db_port=5441
